### PR TITLE
feat(extension,credo): ability to disable Credo extension

### PR DESCRIPTION
**Pull request by mhanberg**

### CODE REVIEW

**Comment by mhanberg** [comment]
Current dependencies on/for this PR:
* main
  * **PR #321** <a href="https://app.graphite.dev/github/pr/elixir-tools/next-ls/321" target="_blank">Graphite</a>  👈
    * **PR #322** <a href="https://app.graphite.dev/github/pr/elixir-tools/next-ls/322" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/elixir-tools/next-ls/321?utm_source=stack-comment).

**Comment by tensiondriven** [comment]
@mhanberg ^

**Comment by mhanberg** [comment]
@mhanberg can you clarify the ping?

**Comment by tensiondriven** [comment]
Oops, I must have commented on the wrong PR.  Here's my original comment:

https://github.com/elixir-tools/next-ls/pull/323#issuecomment-1795395152

And a breakdown of my concern:

1) I'm running elixir-ls via vscode from the Marketplace which is showing v0.11.0
2) To work around issues with credo, I have to manually edit my .credo.exs which is in source control, meaning I have to keep a dirty file around.
3) The ability to configure credo has been fixed and merged into next-ls (thank you 💯 )
4) A release appears to be built for next-ls, but the vscode repo hasn't been updated (not sure if this is a problem)
5) I don't know how to build both elixir-ls and the vscode extension locally such that I can run the code which has the CLI option fix for credo.

So, I'm looking for some guidance - Should I:
1) Wait for the vscode package to be updated/published and update from within vscode
2) Patch my local vscode extension with a build of next-ls from the releases in this repo (if so, does the vscode extension need additional config?)
3) Build local versions of next-ls and the vscode extension?  (if so, what configuration is required?)

Sorry if this comes off as ignorant or low-effort.  I'm really not sure how the vscode extension interacts with next-ls and could use some guidance!

**Pull request merged**
